[package]
name = "taizen"
license = "MIT"
version = "0.1.0"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
description = "TUI MediaWiki browser"
repository = "https://github.com/NerdyPepper/taizen"
readme = "readme.md"
keywords = ["wikipedia", "tui", "app", "curses"]
categories = ["command-line-utilities"]

[dependencies]
reqwest = "0.9.5"
serde_json = "1.0.33"
cursive = "0.9.2"
regex = "1"
url = "1.7.2"
clap = "2.32.0"
lazy_static = "1.0.2"
dirs = "2.0.2"
